/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SmartwatchesRouteImport } from './routes/smartwatches'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as NotebooksRouteImport } from './routes/notebooks'
import { Route as MelhoresCelularesXiaomiRouteImport } from './routes/melhores-celulares-xiaomi'
import { Route as MelhoresCelularesSamsungRouteImport } from './routes/melhores-celulares-samsung'
import { Route as MelhoresCelularesCustoBeneficioRouteImport } from './routes/melhores-celulares-custo-beneficio'
import { Route as MelhoresCelularesAte2500RouteImport } from './routes/melhores-celulares-ate-2500'
import { Route as MelhoresCelularesAte2000RouteImport } from './routes/melhores-celulares-ate-2000'
import { Route as GuiasDeCompraRouteImport } from './routes/guias-de-compra'
import { Route as DivulgacaoDeAfiliadosRouteImport } from './routes/divulgacao-de-afiliados'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComparativosRouteImport } from './routes/comparativos'
import { Route as ComparativoGalaxyA55VsGalaxyA35RouteImport } from './routes/comparativo-galaxy-a55-vs-galaxy-a35'
import { Route as CelularesRouteImport } from './routes/celulares'
import { Route as AcessoriosRouteImport } from './routes/acessorios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewRedmiNote14ProPlusRouteImport } from './routes/review.redmi-note-14-pro-plus'
import { Route as ReviewRedmiNote13ProRouteImport } from './routes/review.redmi-note-13-pro'
import { Route as ReviewPocoX6ProRouteImport } from './routes/review.poco-x6-pro'
import { Route as ReviewIphone15RouteImport } from './routes/review.iphone-15'
import { Route as ReviewGalaxyS24RouteImport } from './routes/review.galaxy-s24'
import { Route as ReviewGalaxyA55RouteImport } from './routes/review.galaxy-a55'
import { Route as ReviewGalaxyA35RouteImport } from './routes/review.galaxy-a35'
import { Route as GuiaMelhoresCelularesParaJogosAte2000RouteImport } from './routes/guia.melhores-celulares-para-jogos-ate-2000'
import { Route as GuiaMelhoresCelularesAte3500ReaisRouteImport } from './routes/guia.melhores-celulares-ate-3500-reais'
import { Route as GuiaMelhoresCelularesAte3000ReaisRouteImport } from './routes/guia.melhores-celulares-ate-3000-reais'
import { Route as GuiaMelhoresCelularesAte2000ReaisRouteImport } from './routes/guia.melhores-celulares-ate-2000-reais'
import { Route as GuiaMelhoresCelularesAte1500ReaisRouteImport } from './routes/guia.melhores-celulares-ate-1500-reais'
import { Route as ComparativoIphone15VsGalaxyS24RouteImport } from './routes/comparativo.iphone-15-vs-galaxy-s24'
import { Route as ComparativoGalaxyA55VsRedmiNote13ProRouteImport } from './routes/comparativo.galaxy-a55-vs-redmi-note-13-pro'
import { Route as ComparativoGalaxyA55VsPocoX6ProRouteImport } from './routes/comparativo.galaxy-a55-vs-poco-x6-pro'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartwatchesRoute = SmartwatchesRouteImport.update({
  id: '/smartwatches',
  path: '/smartwatches',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksRoute = NotebooksRouteImport.update({
  id: '/notebooks',
  path: '/notebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const MelhoresCelularesXiaomiRoute = MelhoresCelularesXiaomiRouteImport.update({
  id: '/melhores-celulares-xiaomi',
  path: '/melhores-celulares-xiaomi',
  getParentRoute: () => rootRouteImport,
} as any)
const MelhoresCelularesSamsungRoute =
  MelhoresCelularesSamsungRouteImport.update({
    id: '/melhores-celulares-samsung',
    path: '/melhores-celulares-samsung',
    getParentRoute: () => rootRouteImport,
  } as any)
const MelhoresCelularesCustoBeneficioRoute =
  MelhoresCelularesCustoBeneficioRouteImport.update({
    id: '/melhores-celulares-custo-beneficio',
    path: '/melhores-celulares-custo-beneficio',
    getParentRoute: () => rootRouteImport,
  } as any)
const MelhoresCelularesAte2500Route =
  MelhoresCelularesAte2500RouteImport.update({
    id: '/melhores-celulares-ate-2500',
    path: '/melhores-celulares-ate-2500',
    getParentRoute: () => rootRouteImport,
  } as any)
const MelhoresCelularesAte2000Route =
  MelhoresCelularesAte2000RouteImport.update({
    id: '/melhores-celulares-ate-2000',
    path: '/melhores-celulares-ate-2000',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuiasDeCompraRoute = GuiasDeCompraRouteImport.update({
  id: '/guias-de-compra',
  path: '/guias-de-compra',
  getParentRoute: () => rootRouteImport,
} as any)
const DivulgacaoDeAfiliadosRoute = DivulgacaoDeAfiliadosRouteImport.update({
  id: '/divulgacao-de-afiliados',
  path: '/divulgacao-de-afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativosRoute = ComparativosRouteImport.update({
  id: '/comparativos',
  path: '/comparativos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativoGalaxyA55VsGalaxyA35Route =
  ComparativoGalaxyA55VsGalaxyA35RouteImport.update({
    id: '/comparativo-galaxy-a55-vs-galaxy-a35',
    path: '/comparativo-galaxy-a55-vs-galaxy-a35',
    getParentRoute: () => rootRouteImport,
  } as any)
const CelularesRoute = CelularesRouteImport.update({
  id: '/celulares',
  path: '/celulares',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoriosRoute = AcessoriosRouteImport.update({
  id: '/acessorios',
  path: '/acessorios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRedmiNote14ProPlusRoute =
  ReviewRedmiNote14ProPlusRouteImport.update({
    id: '/review/redmi-note-14-pro-plus',
    path: '/review/redmi-note-14-pro-plus',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReviewRedmiNote13ProRoute = ReviewRedmiNote13ProRouteImport.update({
  id: '/review/redmi-note-13-pro',
  path: '/review/redmi-note-13-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewPocoX6ProRoute = ReviewPocoX6ProRouteImport.update({
  id: '/review/poco-x6-pro',
  path: '/review/poco-x6-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIphone15Route = ReviewIphone15RouteImport.update({
  id: '/review/iphone-15',
  path: '/review/iphone-15',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewGalaxyS24Route = ReviewGalaxyS24RouteImport.update({
  id: '/review/galaxy-s24',
  path: '/review/galaxy-s24',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewGalaxyA55Route = ReviewGalaxyA55RouteImport.update({
  id: '/review/galaxy-a55',
  path: '/review/galaxy-a55',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewGalaxyA35Route = ReviewGalaxyA35RouteImport.update({
  id: '/review/galaxy-a35',
  path: '/review/galaxy-a35',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaMelhoresCelularesParaJogosAte2000Route =
  GuiaMelhoresCelularesParaJogosAte2000RouteImport.update({
    id: '/guia/melhores-celulares-para-jogos-ate-2000',
    path: '/guia/melhores-celulares-para-jogos-ate-2000',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuiaMelhoresCelularesAte3500ReaisRoute =
  GuiaMelhoresCelularesAte3500ReaisRouteImport.update({
    id: '/guia/melhores-celulares-ate-3500-reais',
    path: '/guia/melhores-celulares-ate-3500-reais',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuiaMelhoresCelularesAte3000ReaisRoute =
  GuiaMelhoresCelularesAte3000ReaisRouteImport.update({
    id: '/guia/melhores-celulares-ate-3000-reais',
    path: '/guia/melhores-celulares-ate-3000-reais',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuiaMelhoresCelularesAte2000ReaisRoute =
  GuiaMelhoresCelularesAte2000ReaisRouteImport.update({
    id: '/guia/melhores-celulares-ate-2000-reais',
    path: '/guia/melhores-celulares-ate-2000-reais',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuiaMelhoresCelularesAte1500ReaisRoute =
  GuiaMelhoresCelularesAte1500ReaisRouteImport.update({
    id: '/guia/melhores-celulares-ate-1500-reais',
    path: '/guia/melhores-celulares-ate-1500-reais',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComparativoIphone15VsGalaxyS24Route =
  ComparativoIphone15VsGalaxyS24RouteImport.update({
    id: '/comparativo/iphone-15-vs-galaxy-s24',
    path: '/comparativo/iphone-15-vs-galaxy-s24',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComparativoGalaxyA55VsRedmiNote13ProRoute =
  ComparativoGalaxyA55VsRedmiNote13ProRouteImport.update({
    id: '/comparativo/galaxy-a55-vs-redmi-note-13-pro',
    path: '/comparativo/galaxy-a55-vs-redmi-note-13-pro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComparativoGalaxyA55VsPocoX6ProRoute =
  ComparativoGalaxyA55VsPocoX6ProRouteImport.update({
    id: '/comparativo/galaxy-a55-vs-poco-x6-pro',
    path: '/comparativo/galaxy-a55-vs-poco-x6-pro',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessorios': typeof AcessoriosRoute
  '/celulares': typeof CelularesRoute
  '/comparativo-galaxy-a55-vs-galaxy-a35': typeof ComparativoGalaxyA55VsGalaxyA35Route
  '/comparativos': typeof ComparativosRoute
  '/contato': typeof ContatoRoute
  '/divulgacao-de-afiliados': typeof DivulgacaoDeAfiliadosRoute
  '/guias-de-compra': typeof GuiasDeCompraRoute
  '/melhores-celulares-ate-2000': typeof MelhoresCelularesAte2000Route
  '/melhores-celulares-ate-2500': typeof MelhoresCelularesAte2500Route
  '/melhores-celulares-custo-beneficio': typeof MelhoresCelularesCustoBeneficioRoute
  '/melhores-celulares-samsung': typeof MelhoresCelularesSamsungRoute
  '/melhores-celulares-xiaomi': typeof MelhoresCelularesXiaomiRoute
  '/notebooks': typeof NotebooksRoute
  '/ofertas': typeof OfertasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/smartwatches': typeof SmartwatchesRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/transparencia': typeof TransparenciaRoute
  '/comparativo/galaxy-a55-vs-poco-x6-pro': typeof ComparativoGalaxyA55VsPocoX6ProRoute
  '/comparativo/galaxy-a55-vs-redmi-note-13-pro': typeof ComparativoGalaxyA55VsRedmiNote13ProRoute
  '/comparativo/iphone-15-vs-galaxy-s24': typeof ComparativoIphone15VsGalaxyS24Route
  '/guia/melhores-celulares-ate-1500-reais': typeof GuiaMelhoresCelularesAte1500ReaisRoute
  '/guia/melhores-celulares-ate-2000-reais': typeof GuiaMelhoresCelularesAte2000ReaisRoute
  '/guia/melhores-celulares-ate-3000-reais': typeof GuiaMelhoresCelularesAte3000ReaisRoute
  '/guia/melhores-celulares-ate-3500-reais': typeof GuiaMelhoresCelularesAte3500ReaisRoute
  '/guia/melhores-celulares-para-jogos-ate-2000': typeof GuiaMelhoresCelularesParaJogosAte2000Route
  '/review/galaxy-a35': typeof ReviewGalaxyA35Route
  '/review/galaxy-a55': typeof ReviewGalaxyA55Route
  '/review/galaxy-s24': typeof ReviewGalaxyS24Route
  '/review/iphone-15': typeof ReviewIphone15Route
  '/review/poco-x6-pro': typeof ReviewPocoX6ProRoute
  '/review/redmi-note-13-pro': typeof ReviewRedmiNote13ProRoute
  '/review/redmi-note-14-pro-plus': typeof ReviewRedmiNote14ProPlusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessorios': typeof AcessoriosRoute
  '/celulares': typeof CelularesRoute
  '/comparativo-galaxy-a55-vs-galaxy-a35': typeof ComparativoGalaxyA55VsGalaxyA35Route
  '/comparativos': typeof ComparativosRoute
  '/contato': typeof ContatoRoute
  '/divulgacao-de-afiliados': typeof DivulgacaoDeAfiliadosRoute
  '/guias-de-compra': typeof GuiasDeCompraRoute
  '/melhores-celulares-ate-2000': typeof MelhoresCelularesAte2000Route
  '/melhores-celulares-ate-2500': typeof MelhoresCelularesAte2500Route
  '/melhores-celulares-custo-beneficio': typeof MelhoresCelularesCustoBeneficioRoute
  '/melhores-celulares-samsung': typeof MelhoresCelularesSamsungRoute
  '/melhores-celulares-xiaomi': typeof MelhoresCelularesXiaomiRoute
  '/notebooks': typeof NotebooksRoute
  '/ofertas': typeof OfertasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/smartwatches': typeof SmartwatchesRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/transparencia': typeof TransparenciaRoute
  '/comparativo/galaxy-a55-vs-poco-x6-pro': typeof ComparativoGalaxyA55VsPocoX6ProRoute
  '/comparativo/galaxy-a55-vs-redmi-note-13-pro': typeof ComparativoGalaxyA55VsRedmiNote13ProRoute
  '/comparativo/iphone-15-vs-galaxy-s24': typeof ComparativoIphone15VsGalaxyS24Route
  '/guia/melhores-celulares-ate-1500-reais': typeof GuiaMelhoresCelularesAte1500ReaisRoute
  '/guia/melhores-celulares-ate-2000-reais': typeof GuiaMelhoresCelularesAte2000ReaisRoute
  '/guia/melhores-celulares-ate-3000-reais': typeof GuiaMelhoresCelularesAte3000ReaisRoute
  '/guia/melhores-celulares-ate-3500-reais': typeof GuiaMelhoresCelularesAte3500ReaisRoute
  '/guia/melhores-celulares-para-jogos-ate-2000': typeof GuiaMelhoresCelularesParaJogosAte2000Route
  '/review/galaxy-a35': typeof ReviewGalaxyA35Route
  '/review/galaxy-a55': typeof ReviewGalaxyA55Route
  '/review/galaxy-s24': typeof ReviewGalaxyS24Route
  '/review/iphone-15': typeof ReviewIphone15Route
  '/review/poco-x6-pro': typeof ReviewPocoX6ProRoute
  '/review/redmi-note-13-pro': typeof ReviewRedmiNote13ProRoute
  '/review/redmi-note-14-pro-plus': typeof ReviewRedmiNote14ProPlusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acessorios': typeof AcessoriosRoute
  '/celulares': typeof CelularesRoute
  '/comparativo-galaxy-a55-vs-galaxy-a35': typeof ComparativoGalaxyA55VsGalaxyA35Route
  '/comparativos': typeof ComparativosRoute
  '/contato': typeof ContatoRoute
  '/divulgacao-de-afiliados': typeof DivulgacaoDeAfiliadosRoute
  '/guias-de-compra': typeof GuiasDeCompraRoute
  '/melhores-celulares-ate-2000': typeof MelhoresCelularesAte2000Route
  '/melhores-celulares-ate-2500': typeof MelhoresCelularesAte2500Route
  '/melhores-celulares-custo-beneficio': typeof MelhoresCelularesCustoBeneficioRoute
  '/melhores-celulares-samsung': typeof MelhoresCelularesSamsungRoute
  '/melhores-celulares-xiaomi': typeof MelhoresCelularesXiaomiRoute
  '/notebooks': typeof NotebooksRoute
  '/ofertas': typeof OfertasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/smartwatches': typeof SmartwatchesRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/transparencia': typeof TransparenciaRoute
  '/comparativo/galaxy-a55-vs-poco-x6-pro': typeof ComparativoGalaxyA55VsPocoX6ProRoute
  '/comparativo/galaxy-a55-vs-redmi-note-13-pro': typeof ComparativoGalaxyA55VsRedmiNote13ProRoute
  '/comparativo/iphone-15-vs-galaxy-s24': typeof ComparativoIphone15VsGalaxyS24Route
  '/guia/melhores-celulares-ate-1500-reais': typeof GuiaMelhoresCelularesAte1500ReaisRoute
  '/guia/melhores-celulares-ate-2000-reais': typeof GuiaMelhoresCelularesAte2000ReaisRoute
  '/guia/melhores-celulares-ate-3000-reais': typeof GuiaMelhoresCelularesAte3000ReaisRoute
  '/guia/melhores-celulares-ate-3500-reais': typeof GuiaMelhoresCelularesAte3500ReaisRoute
  '/guia/melhores-celulares-para-jogos-ate-2000': typeof GuiaMelhoresCelularesParaJogosAte2000Route
  '/review/galaxy-a35': typeof ReviewGalaxyA35Route
  '/review/galaxy-a55': typeof ReviewGalaxyA55Route
  '/review/galaxy-s24': typeof ReviewGalaxyS24Route
  '/review/iphone-15': typeof ReviewIphone15Route
  '/review/poco-x6-pro': typeof ReviewPocoX6ProRoute
  '/review/redmi-note-13-pro': typeof ReviewRedmiNote13ProRoute
  '/review/redmi-note-14-pro-plus': typeof ReviewRedmiNote14ProPlusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessorios'
    | '/celulares'
    | '/comparativo-galaxy-a55-vs-galaxy-a35'
    | '/comparativos'
    | '/contato'
    | '/divulgacao-de-afiliados'
    | '/guias-de-compra'
    | '/melhores-celulares-ate-2000'
    | '/melhores-celulares-ate-2500'
    | '/melhores-celulares-custo-beneficio'
    | '/melhores-celulares-samsung'
    | '/melhores-celulares-xiaomi'
    | '/notebooks'
    | '/ofertas'
    | '/politica-de-privacidade'
    | '/smartwatches'
    | '/sobre'
    | '/termos-de-uso'
    | '/transparencia'
    | '/comparativo/galaxy-a55-vs-poco-x6-pro'
    | '/comparativo/galaxy-a55-vs-redmi-note-13-pro'
    | '/comparativo/iphone-15-vs-galaxy-s24'
    | '/guia/melhores-celulares-ate-1500-reais'
    | '/guia/melhores-celulares-ate-2000-reais'
    | '/guia/melhores-celulares-ate-3000-reais'
    | '/guia/melhores-celulares-ate-3500-reais'
    | '/guia/melhores-celulares-para-jogos-ate-2000'
    | '/review/galaxy-a35'
    | '/review/galaxy-a55'
    | '/review/galaxy-s24'
    | '/review/iphone-15'
    | '/review/poco-x6-pro'
    | '/review/redmi-note-13-pro'
    | '/review/redmi-note-14-pro-plus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessorios'
    | '/celulares'
    | '/comparativo-galaxy-a55-vs-galaxy-a35'
    | '/comparativos'
    | '/contato'
    | '/divulgacao-de-afiliados'
    | '/guias-de-compra'
    | '/melhores-celulares-ate-2000'
    | '/melhores-celulares-ate-2500'
    | '/melhores-celulares-custo-beneficio'
    | '/melhores-celulares-samsung'
    | '/melhores-celulares-xiaomi'
    | '/notebooks'
    | '/ofertas'
    | '/politica-de-privacidade'
    | '/smartwatches'
    | '/sobre'
    | '/termos-de-uso'
    | '/transparencia'
    | '/comparativo/galaxy-a55-vs-poco-x6-pro'
    | '/comparativo/galaxy-a55-vs-redmi-note-13-pro'
    | '/comparativo/iphone-15-vs-galaxy-s24'
    | '/guia/melhores-celulares-ate-1500-reais'
    | '/guia/melhores-celulares-ate-2000-reais'
    | '/guia/melhores-celulares-ate-3000-reais'
    | '/guia/melhores-celulares-ate-3500-reais'
    | '/guia/melhores-celulares-para-jogos-ate-2000'
    | '/review/galaxy-a35'
    | '/review/galaxy-a55'
    | '/review/galaxy-s24'
    | '/review/iphone-15'
    | '/review/poco-x6-pro'
    | '/review/redmi-note-13-pro'
    | '/review/redmi-note-14-pro-plus'
  id:
    | '__root__'
    | '/'
    | '/acessorios'
    | '/celulares'
    | '/comparativo-galaxy-a55-vs-galaxy-a35'
    | '/comparativos'
    | '/contato'
    | '/divulgacao-de-afiliados'
    | '/guias-de-compra'
    | '/melhores-celulares-ate-2000'
    | '/melhores-celulares-ate-2500'
    | '/melhores-celulares-custo-beneficio'
    | '/melhores-celulares-samsung'
    | '/melhores-celulares-xiaomi'
    | '/notebooks'
    | '/ofertas'
    | '/politica-de-privacidade'
    | '/smartwatches'
    | '/sobre'
    | '/termos-de-uso'
    | '/transparencia'
    | '/comparativo/galaxy-a55-vs-poco-x6-pro'
    | '/comparativo/galaxy-a55-vs-redmi-note-13-pro'
    | '/comparativo/iphone-15-vs-galaxy-s24'
    | '/guia/melhores-celulares-ate-1500-reais'
    | '/guia/melhores-celulares-ate-2000-reais'
    | '/guia/melhores-celulares-ate-3000-reais'
    | '/guia/melhores-celulares-ate-3500-reais'
    | '/guia/melhores-celulares-para-jogos-ate-2000'
    | '/review/galaxy-a35'
    | '/review/galaxy-a55'
    | '/review/galaxy-s24'
    | '/review/iphone-15'
    | '/review/poco-x6-pro'
    | '/review/redmi-note-13-pro'
    | '/review/redmi-note-14-pro-plus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoriosRoute: typeof AcessoriosRoute
  CelularesRoute: typeof CelularesRoute
  ComparativoGalaxyA55VsGalaxyA35Route: typeof ComparativoGalaxyA55VsGalaxyA35Route
  ComparativosRoute: typeof ComparativosRoute
  ContatoRoute: typeof ContatoRoute
  DivulgacaoDeAfiliadosRoute: typeof DivulgacaoDeAfiliadosRoute
  GuiasDeCompraRoute: typeof GuiasDeCompraRoute
  MelhoresCelularesAte2000Route: typeof MelhoresCelularesAte2000Route
  MelhoresCelularesAte2500Route: typeof MelhoresCelularesAte2500Route
  MelhoresCelularesCustoBeneficioRoute: typeof MelhoresCelularesCustoBeneficioRoute
  MelhoresCelularesSamsungRoute: typeof MelhoresCelularesSamsungRoute
  MelhoresCelularesXiaomiRoute: typeof MelhoresCelularesXiaomiRoute
  NotebooksRoute: typeof NotebooksRoute
  OfertasRoute: typeof OfertasRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SmartwatchesRoute: typeof SmartwatchesRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  TransparenciaRoute: typeof TransparenciaRoute
  ComparativoGalaxyA55VsPocoX6ProRoute: typeof ComparativoGalaxyA55VsPocoX6ProRoute
  ComparativoGalaxyA55VsRedmiNote13ProRoute: typeof ComparativoGalaxyA55VsRedmiNote13ProRoute
  ComparativoIphone15VsGalaxyS24Route: typeof ComparativoIphone15VsGalaxyS24Route
  GuiaMelhoresCelularesAte1500ReaisRoute: typeof GuiaMelhoresCelularesAte1500ReaisRoute
  GuiaMelhoresCelularesAte2000ReaisRoute: typeof GuiaMelhoresCelularesAte2000ReaisRoute
  GuiaMelhoresCelularesAte3000ReaisRoute: typeof GuiaMelhoresCelularesAte3000ReaisRoute
  GuiaMelhoresCelularesAte3500ReaisRoute: typeof GuiaMelhoresCelularesAte3500ReaisRoute
  GuiaMelhoresCelularesParaJogosAte2000Route: typeof GuiaMelhoresCelularesParaJogosAte2000Route
  ReviewGalaxyA35Route: typeof ReviewGalaxyA35Route
  ReviewGalaxyA55Route: typeof ReviewGalaxyA55Route
  ReviewGalaxyS24Route: typeof ReviewGalaxyS24Route
  ReviewIphone15Route: typeof ReviewIphone15Route
  ReviewPocoX6ProRoute: typeof ReviewPocoX6ProRoute
  ReviewRedmiNote13ProRoute: typeof ReviewRedmiNote13ProRoute
  ReviewRedmiNote14ProPlusRoute: typeof ReviewRedmiNote14ProPlusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smartwatches': {
      id: '/smartwatches'
      path: '/smartwatches'
      fullPath: '/smartwatches'
      preLoaderRoute: typeof SmartwatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks': {
      id: '/notebooks'
      path: '/notebooks'
      fullPath: '/notebooks'
      preLoaderRoute: typeof NotebooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melhores-celulares-xiaomi': {
      id: '/melhores-celulares-xiaomi'
      path: '/melhores-celulares-xiaomi'
      fullPath: '/melhores-celulares-xiaomi'
      preLoaderRoute: typeof MelhoresCelularesXiaomiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melhores-celulares-samsung': {
      id: '/melhores-celulares-samsung'
      path: '/melhores-celulares-samsung'
      fullPath: '/melhores-celulares-samsung'
      preLoaderRoute: typeof MelhoresCelularesSamsungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melhores-celulares-custo-beneficio': {
      id: '/melhores-celulares-custo-beneficio'
      path: '/melhores-celulares-custo-beneficio'
      fullPath: '/melhores-celulares-custo-beneficio'
      preLoaderRoute: typeof MelhoresCelularesCustoBeneficioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melhores-celulares-ate-2500': {
      id: '/melhores-celulares-ate-2500'
      path: '/melhores-celulares-ate-2500'
      fullPath: '/melhores-celulares-ate-2500'
      preLoaderRoute: typeof MelhoresCelularesAte2500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melhores-celulares-ate-2000': {
      id: '/melhores-celulares-ate-2000'
      path: '/melhores-celulares-ate-2000'
      fullPath: '/melhores-celulares-ate-2000'
      preLoaderRoute: typeof MelhoresCelularesAte2000RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias-de-compra': {
      id: '/guias-de-compra'
      path: '/guias-de-compra'
      fullPath: '/guias-de-compra'
      preLoaderRoute: typeof GuiasDeCompraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divulgacao-de-afiliados': {
      id: '/divulgacao-de-afiliados'
      path: '/divulgacao-de-afiliados'
      fullPath: '/divulgacao-de-afiliados'
      preLoaderRoute: typeof DivulgacaoDeAfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativos': {
      id: '/comparativos'
      path: '/comparativos'
      fullPath: '/comparativos'
      preLoaderRoute: typeof ComparativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativo-galaxy-a55-vs-galaxy-a35': {
      id: '/comparativo-galaxy-a55-vs-galaxy-a35'
      path: '/comparativo-galaxy-a55-vs-galaxy-a35'
      fullPath: '/comparativo-galaxy-a55-vs-galaxy-a35'
      preLoaderRoute: typeof ComparativoGalaxyA55VsGalaxyA35RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celulares': {
      id: '/celulares'
      path: '/celulares'
      fullPath: '/celulares'
      preLoaderRoute: typeof CelularesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessorios': {
      id: '/acessorios'
      path: '/acessorios'
      fullPath: '/acessorios'
      preLoaderRoute: typeof AcessoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/redmi-note-14-pro-plus': {
      id: '/review/redmi-note-14-pro-plus'
      path: '/review/redmi-note-14-pro-plus'
      fullPath: '/review/redmi-note-14-pro-plus'
      preLoaderRoute: typeof ReviewRedmiNote14ProPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/redmi-note-13-pro': {
      id: '/review/redmi-note-13-pro'
      path: '/review/redmi-note-13-pro'
      fullPath: '/review/redmi-note-13-pro'
      preLoaderRoute: typeof ReviewRedmiNote13ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/poco-x6-pro': {
      id: '/review/poco-x6-pro'
      path: '/review/poco-x6-pro'
      fullPath: '/review/poco-x6-pro'
      preLoaderRoute: typeof ReviewPocoX6ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/iphone-15': {
      id: '/review/iphone-15'
      path: '/review/iphone-15'
      fullPath: '/review/iphone-15'
      preLoaderRoute: typeof ReviewIphone15RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/galaxy-s24': {
      id: '/review/galaxy-s24'
      path: '/review/galaxy-s24'
      fullPath: '/review/galaxy-s24'
      preLoaderRoute: typeof ReviewGalaxyS24RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/galaxy-a55': {
      id: '/review/galaxy-a55'
      path: '/review/galaxy-a55'
      fullPath: '/review/galaxy-a55'
      preLoaderRoute: typeof ReviewGalaxyA55RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/galaxy-a35': {
      id: '/review/galaxy-a35'
      path: '/review/galaxy-a35'
      fullPath: '/review/galaxy-a35'
      preLoaderRoute: typeof ReviewGalaxyA35RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/melhores-celulares-para-jogos-ate-2000': {
      id: '/guia/melhores-celulares-para-jogos-ate-2000'
      path: '/guia/melhores-celulares-para-jogos-ate-2000'
      fullPath: '/guia/melhores-celulares-para-jogos-ate-2000'
      preLoaderRoute: typeof GuiaMelhoresCelularesParaJogosAte2000RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/melhores-celulares-ate-3500-reais': {
      id: '/guia/melhores-celulares-ate-3500-reais'
      path: '/guia/melhores-celulares-ate-3500-reais'
      fullPath: '/guia/melhores-celulares-ate-3500-reais'
      preLoaderRoute: typeof GuiaMelhoresCelularesAte3500ReaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/melhores-celulares-ate-3000-reais': {
      id: '/guia/melhores-celulares-ate-3000-reais'
      path: '/guia/melhores-celulares-ate-3000-reais'
      fullPath: '/guia/melhores-celulares-ate-3000-reais'
      preLoaderRoute: typeof GuiaMelhoresCelularesAte3000ReaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/melhores-celulares-ate-2000-reais': {
      id: '/guia/melhores-celulares-ate-2000-reais'
      path: '/guia/melhores-celulares-ate-2000-reais'
      fullPath: '/guia/melhores-celulares-ate-2000-reais'
      preLoaderRoute: typeof GuiaMelhoresCelularesAte2000ReaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/melhores-celulares-ate-1500-reais': {
      id: '/guia/melhores-celulares-ate-1500-reais'
      path: '/guia/melhores-celulares-ate-1500-reais'
      fullPath: '/guia/melhores-celulares-ate-1500-reais'
      preLoaderRoute: typeof GuiaMelhoresCelularesAte1500ReaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativo/iphone-15-vs-galaxy-s24': {
      id: '/comparativo/iphone-15-vs-galaxy-s24'
      path: '/comparativo/iphone-15-vs-galaxy-s24'
      fullPath: '/comparativo/iphone-15-vs-galaxy-s24'
      preLoaderRoute: typeof ComparativoIphone15VsGalaxyS24RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativo/galaxy-a55-vs-redmi-note-13-pro': {
      id: '/comparativo/galaxy-a55-vs-redmi-note-13-pro'
      path: '/comparativo/galaxy-a55-vs-redmi-note-13-pro'
      fullPath: '/comparativo/galaxy-a55-vs-redmi-note-13-pro'
      preLoaderRoute: typeof ComparativoGalaxyA55VsRedmiNote13ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativo/galaxy-a55-vs-poco-x6-pro': {
      id: '/comparativo/galaxy-a55-vs-poco-x6-pro'
      path: '/comparativo/galaxy-a55-vs-poco-x6-pro'
      fullPath: '/comparativo/galaxy-a55-vs-poco-x6-pro'
      preLoaderRoute: typeof ComparativoGalaxyA55VsPocoX6ProRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoriosRoute: AcessoriosRoute,
  CelularesRoute: CelularesRoute,
  ComparativoGalaxyA55VsGalaxyA35Route: ComparativoGalaxyA55VsGalaxyA35Route,
  ComparativosRoute: ComparativosRoute,
  ContatoRoute: ContatoRoute,
  DivulgacaoDeAfiliadosRoute: DivulgacaoDeAfiliadosRoute,
  GuiasDeCompraRoute: GuiasDeCompraRoute,
  MelhoresCelularesAte2000Route: MelhoresCelularesAte2000Route,
  MelhoresCelularesAte2500Route: MelhoresCelularesAte2500Route,
  MelhoresCelularesCustoBeneficioRoute: MelhoresCelularesCustoBeneficioRoute,
  MelhoresCelularesSamsungRoute: MelhoresCelularesSamsungRoute,
  MelhoresCelularesXiaomiRoute: MelhoresCelularesXiaomiRoute,
  NotebooksRoute: NotebooksRoute,
  OfertasRoute: OfertasRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SmartwatchesRoute: SmartwatchesRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  TransparenciaRoute: TransparenciaRoute,
  ComparativoGalaxyA55VsPocoX6ProRoute: ComparativoGalaxyA55VsPocoX6ProRoute,
  ComparativoGalaxyA55VsRedmiNote13ProRoute:
    ComparativoGalaxyA55VsRedmiNote13ProRoute,
  ComparativoIphone15VsGalaxyS24Route: ComparativoIphone15VsGalaxyS24Route,
  GuiaMelhoresCelularesAte1500ReaisRoute:
    GuiaMelhoresCelularesAte1500ReaisRoute,
  GuiaMelhoresCelularesAte2000ReaisRoute:
    GuiaMelhoresCelularesAte2000ReaisRoute,
  GuiaMelhoresCelularesAte3000ReaisRoute:
    GuiaMelhoresCelularesAte3000ReaisRoute,
  GuiaMelhoresCelularesAte3500ReaisRoute:
    GuiaMelhoresCelularesAte3500ReaisRoute,
  GuiaMelhoresCelularesParaJogosAte2000Route:
    GuiaMelhoresCelularesParaJogosAte2000Route,
  ReviewGalaxyA35Route: ReviewGalaxyA35Route,
  ReviewGalaxyA55Route: ReviewGalaxyA55Route,
  ReviewGalaxyS24Route: ReviewGalaxyS24Route,
  ReviewIphone15Route: ReviewIphone15Route,
  ReviewPocoX6ProRoute: ReviewPocoX6ProRoute,
  ReviewRedmiNote13ProRoute: ReviewRedmiNote13ProRoute,
  ReviewRedmiNote14ProPlusRoute: ReviewRedmiNote14ProPlusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
